version: '2'

services:
    shinyproxy:
        build:
            context: ./
        ports:
            - 8085:8085
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks: 
            - sifa-net

networks: 
    sifa-net:
        external: true
